/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_v1_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_v1_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread State */
        get: operations["get_thread_state_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        /** Delete Thread */
        delete: operations["delete_thread_v1_threads__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/runs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream */
        post: operations["stream_v1_threads__thread_id__runs_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/runs/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_v1_threads__thread_id__runs_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/runs/wait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wait
         * @description Execução síncrona, para consumidores que não querem lidar com SSE.
         */
        post: operations["wait_v1_threads__thread_id__runs_wait_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateThreadIn */
        CreateThreadIn: {
            /** Title */
            title?: string | null;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterruptOut */
        InterruptOut: {
            /** Id */
            id: string | null;
            /** Value */
            value: unknown;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "human" | "ai" | "tool" | "system";
            /** Content */
            content: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallOut"][];
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id: string | null;
            /**
             * Name
             * @default null
             */
            name: string | null;
        };
        /** ResumeIn */
        ResumeIn: {
            /** Value */
            value: unknown;
            /**
             * Interrupt Id
             * @description Necessário só quando há mais de um interrupt pendente.
             */
            interrupt_id?: string | null;
        };
        /** RunIn */
        RunIn: {
            /** Message */
            message: string;
        };
        /** ThreadOut */
        ThreadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ThreadStateOut */
        ThreadStateOut: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            /** Next */
            next: string[];
            /** Interrupts */
            interrupts: components["schemas"]["InterruptOut"][];
        };
        /** ToolCallOut */
        ToolCallOut: {
            /** Id */
            id: string | null;
            /** Name */
            name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** DoneEvent */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "done";
            /** Run Id */
            run_id: string;
            /** Interrupted */
            interrupted: boolean;
            /** Next */
            next: string[];
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "error";
            /**
             * Code
             * @enum {string}
             */
            code: "thread_busy" | "timeout" | "internal";
            /** Message */
            message: string;
        };
        /** InterruptEvent */
        InterruptEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "interrupt";
            /** Interrupt Id */
            interrupt_id: string | null;
            /** Value */
            value: unknown;
        };
        /** MessageEvent */
        MessageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "message";
            /** Node */
            node: string;
            message: components["schemas"]["MessageOut"];
        };
        /** RunStartedEvent */
        RunStartedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "run_started";
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
        };
        /** TokenEvent */
        TokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "token";
            /** Message Id */
            message_id: string | null;
            /** Content */
            content: string;
        };
        StreamEvent: components["schemas"]["RunStartedEvent"] | components["schemas"]["TokenEvent"] | components["schemas"]["MessageEvent"] | components["schemas"]["InterruptEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_threads_v1_threads_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_v1_threads_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_state_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_v1_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_v1_threads__thread_id__runs_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Stream SSE. Cada evento tem `event:` igual ao campo `event` do payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_v1_threads__thread_id__runs_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeIn"];
            };
        };
        responses: {
            /** @description Stream SSE. Cada evento tem `event:` igual ao campo `event` do payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wait_v1_threads__thread_id__runs_wait_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadStateOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
